import { readFile, readdir, stat } from "node:fs/promises";
import { join, relative } from "node:path";
const root=process.cwd();
const required=["index.html","courses.html","videos.html","pricing.html","login/index.html","signup/index.html","payment/index.html","checkout/index.html","account/devices/index.html","account/activation/index.html","activation/index.html","private-booking/index.html","level-test/index.html","live/index.html","lesson/index.html","admin/index.html","admin/courses/index.html","admin/videos/index.html","admin/homework/index.html","admin/students/index.html","admin/analytics/index.html","admin/codes/index.html","admin/notifications/index.html","admin/comments/index.html","admin/leaderboard/index.html"];
const errors=[];
for(const file of required){try{const html=await readFile(join(root,file),"utf8");if(!/<html lang="ar" dir="rtl">/.test(html))errors.push(`${file}: missing Arabic RTL root`);const platformShell=html.includes("platform.js")&&html.includes("platform.css");const approvedPublicShell=html.includes("script.js")&&html.includes("styles.css");if(!platformShell&&!approvedPublicShell)errors.push(`${file}: missing approved or platform shell assets`);const ids=[...html.matchAll(/\sid="([^"]+)"/g)].map(m=>m[1]);const dup=[...new Set(ids.filter((x,i)=>ids.indexOf(x)!==i))];if(dup.length)errors.push(`${file}: duplicate ids ${dup.join(",")}`)}catch{errors.push(`${file}: missing`)}}
for(const file of ["platform.js","platform-data.js","script.js","models/platform-models.js"]){const code=await readFile(join(root,file),"utf8");try{new Function(code.replace(/^export\s+/gm,""))}catch(error){errors.push(`${file}: ${error.message}`)}}
for(const file of ["platform.css","styles.css"]){const css=await readFile(join(root,file),"utf8");const a=(css.match(/\{/g)||[]).length,b=(css.match(/\}/g)||[]).length;if(a!==b)errors.push(`${file}: unbalanced braces ${a}/${b}`)}
const combined=await readFile(join(root,"platform.js"),"utf8")+await readFile(join(root,"platform-data.js"),"utf8");for(const marker of ["TODO","السعر قريبًا","لا يمكن","غير مربوط","غير مفعّل"]){if(!combined.includes(marker))errors.push(`missing boundary marker: ${marker}`)}
if(/\$\s*\d|\b(?:EGP|USD)\s*\d|\d+\s*(?:EGP|USD)/i.test(combined))errors.push("invented currency amount found");
if(errors.length){console.error(errors.join("\n"));process.exit(1)}console.log(`Validated ${required.length} Arabic RTL routes, shared scripts, CSS and backend boundaries.`);